### ISSUE TITLE
Externalize keycloak.json file

### ISSUE THREAD

**Issue by pandeybk** [dynamind/grails3-spring-security-keycloak-minimal#1]
Any idea if we can externalize src/main/webapp/WEB-INF/keycloak.json file?

**Comment by dynamind** [comment]
Most keycloak client implementation allow you to initialize in various ways; keycloak.json is just one way. So you could set the authorization url and client secret via environment variables for example.

**Comment by dynamind** [comment]
I mean, you need to read the values from the environment variables and pass them to the correct initialization method

**Comment by dynamind** [comment]
I have a working code example from another project somewhere, but it shouldn’t be hard to figure out by yourself
